spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-admin-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.121:8848

server:
  port: 12000

management:
  endpoints:
    web:
      exposure:
        include: "*"